DATA:
  DATASET: agri17k
  IMG_SIZE: 224
MODEL:
  TYPE: efficientnet_v2
  NAME: efficientnet_v2_s_agri17k
  EFFICIENTNET_V2:
    NAME: efficientnet_v2_s
    DROPOUT: 0.1
    STOCHASTIC_DEPTH: 0.2
TRAIN:
  EPOCHS: 120
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-3
  WARMUP_LR: 1e-7
  MIN_LR: 1e-6
SAVE_FREQ: 50
