DATA:
  DATASET: agri17k
  IMG_SIZE: 224
MODEL:
  TYPE: gfnet
  NAME: vanilla_gfnet_b_agri17k
  GFNET:
    PATCH_SIZE: 16
    IN_CHANS: 3 
    EMBED_DIM: 512
    DEPTH: 19
    MLP_RATIO: 4
    DROP_PATH_RATE: 0.25
TRAIN:
  EPOCHS: 120
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-3
  WARMUP_LR: 1e-7
  MIN_LR: 1e-6
SAVE_FREQ: 50