DATA:
  DATASET: agri17k
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: vit_b_16_224_agri17k
  VIT:
    PATCHES: 16
    EMBED_DIM: 768
    FEEDFORWARD_DIM: 3072
    NUM_HEADS: 12
    NUM_LAYERS: 12
    ATTENTION_DROPOUT_RATE: 0.0
    DROPOUT_RATE: 0.1
    REPRESENTATION_SIZE: 768
    CLASSIFIER: 'token'
    POSITIONAL_EMBEDDING: '1d'
TRAIN:
  EPOCHS: 120
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-3
  WARMUP_LR: 1e-7
  MIN_LR: 1e-6
SAVE_FREQ: 50
