DATA:
  DATASET: agri17k
  IMG_SIZE: 224
MODEL:
  TYPE: VCNN_VCM
  NAME: vcm_tiny_agri17k
  DROP_PATH_RATE: 0.2
  VCM:
    FILTER_STRATEGY1: 27
    FILTER_STRATEGY2: 7
    PRETRAIN_IMAGE_SIZE: 224
    USE_LAYERSCALE: False
    LAYERSCALE_VALUE: 1e-6

    EMBED_DIM: 72
    EMBED_CONV: 7
    DEPTHS: [ 3, 3, 12, 3]
TRAIN:
  EPOCHS: 120
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-3
  WARMUP_LR: 1e-7
  MIN_LR: 1e-6
SAVE_FREQ: 50