MODEL:
  TYPE: convnext
  NAME: convnext_base_224_22kto1kto1k_finetune
  DROP_PATH_RATE: 0.2
  LABEL_SMOOTHING: 0.1
  VCNU_CONVNEXT:
    DIMS: [128, 256, 512, 1024]
    DEPTHS: [ 3, 3, 27, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 0
  WARMUP_LR: 0.
  WEIGHT_DECAY: 1e-08
  BASE_LR: 5e-05
  MIN_LR: 5e-07
  LAYER_DECAY: 0.8
  EFFICIENT_FINETUNE: False
AUG:
  MIXUP: 0.
  CUTMIX: 0.
SAVE_FREQ: 15
