MODEL:
  TYPE: convnext
  NAME: convnext_large_224
  DROP_PATH_RATE: 0.5
  VCNU_CONVNEXT:
    DIMS: [192, 384, 768, 1536]
    DEPTHS: [ 3, 3, 27, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
TRAIN:
  BASE_LR: 4e-3
  MIN_LR: 1e-6
SAVE_FREQ: 30