MODEL:
  TYPE: convnext
  NAME: convnext_base_224
  DROP_PATH_RATE: 0.5
  VCNU_CONVNEXT:
    DIMS: [128, 256, 512, 1024]
    DEPTHS: [ 3, 3, 27, 3]
    LAYER_SCALE_INIT_VALUE: 1e-6
TRAIN:
  WARMUP_EPOCHS: 20
  WEIGHT_DECAY: 0.05
  BASE_LR: 2e-3
  WARMUP_LR: 5e-7
  MIN_LR: 5e-7
  CLIP_GRAD: None  # 使用clip_grad效果好，ACC提高0.1%
SAVE_FREQ: 50
