MODEL:
  TYPE: SelfAttentions
  NAME: SelfAttentions_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.15
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 8, 2 ]
    NUM_HEADS: [ 1, 1, 1, 1 ]
    WINDOW_SIZE: 7
    SAVE_FREQ: 30