DATA:
  IMG_SIZE: 384
MODEL:
  TYPE: VCNN_VCM
  NAME: VCM_tiny_1k_384_finetune
  DROP_PATH_RATE: 0.2
  VCM:
    FILTER_STRATEGY1: 23
    FILTER_STRATEGY2: 7
    USE_LAYERSCALE: False
    LAYERSCALE_VALUE: 1e-6
    PRETRAIN_IMAGE_SIZE: 224

    EMBED_DIM: 72
    EMBED_CONV: 7
    DEPTHS: [ 3, 3, 12, 3]
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05  
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False
SAVE_FREQ: 10