DATA:
  IMG_SIZE: 384
MODEL:
  TYPE: VCNN_VCNUs
  NAME: VCNUs_tiny_1k_384_finetune
  DROP_PATH_RATE: 0.1
  VCM:
    FILTER_STRATEGY1: 27
    FILTER_STRATEGY2: 7
    PRETRAIN_IMAGE_SIZE: 224
    USE_LAYERSCALE: False
    LAYERSCALE_VALUE: 1e-4

    EMBED_DIM: 96
    EMBED_CONV: 7
    DEPTHS: [ 3, 3, 9, 3]
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05  
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False
SAVE_FREQ: 10